
DROP TABLE IF EXISTS wells;
CREATE TABLE wells (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(32) NOT NULL UNIQUE);

DROP TABLE IF EXISTS equipments;
CREATE TABLE equipments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(32) NOT NULL UNIQUE,
	well_id INTEGER,
	FOREIGN KEY (well_id) REFERENCES wells (id));
